### ISSUE TITLE
Using php to upload multiple media files

### ISSUE THREAD

**Issue by l337** [tpyo/amazon-s3-php-class#107]
$bucket = 'cdn.blkbxcg.com/urlifemedia/';
$orderid = Session::get('orderid');
$target_path = $orderid . '/' . $type . '/' . $_FILES['file']['name'][$i];
S3::putObject(
   $_FILES['file']['name'][$i],
   $bucket . 'testing',
   $target_path,
  S3::ACL_PUBLIC_READ_WRITE
);

type is either 'images' or 'video', whenever my script runs it creates the folders and files just fine. Whenever I download the media from transmit file and open it, it says the file is corrupted. When I delete the newly created folder, transmit (ftp program) deletes the folder but it gives me a warning also saying 'couldn't find folder'.

**Comment by LolWalid** [comment]
"file is corrupted" mean that your file is not uploaded properly, you have to pass the tempFileName and not the file name. Try to echo $_FILES['file']["tmp_name"][$i] and be sure it returns a valid path and be sure the file exists. If it is just upload the file using it.

**Comment by l337** [comment]
@LolWalid 
Temp = /Applications/MAMP/tmp/php/phpaKC2XT
Name = twr_website_DOM_01_Est_Pre_BD.jpg

**Comment by l337** [comment]
AH this issue should be closed, I tried using this:
S3::inputResource(fopen($_FILES['file']['tmp_name'][$i], 'rb'), filesize($_FILES['file']['tmp_name'][$i]))
and it worked! :dancers:

**Comment by l337** [comment]
Anybody know why this is working for one s3 bucket but not when I switch to a different one? Set same permissions changed secret, key and bucket.

**Comment by l337** [comment]
well I researched the issue looks like aws doesn't recognize "/" as a path rather than keys, I fixed the issue by creating a new bucket and use US Standard.

Now is there a way to get objects using tpyo's S3 class by date, whenever I get objects, and use a loop it gets those objects by size.

**Comment by tpyo** [comment]
Closing.
