### ISSUE TITLE
How to remove empty folder or folder with files?

### ISSUE THREAD

**Issue by 63ek** [tpyo/amazon-s3-php-class#112]
How to remove empty folder or folder with files?

**Comment by guanche** [comment]
The only safe way to do this (with folders with large number of files at least) is to create your own recursive logic or use the aws-cli.

**Comment by tpyo** [comment]
Sorry for the very late response.  @guanche is correct, Amazon may have added a recursive delete method by now, but I have not checked.  Closing this issue.
