### ISSUE TITLE
deleteObject retrun true when even the file is not deleted 

### ISSUE THREAD

**Issue by aamirdx** [tpyo/amazon-s3-php-class#119]
I am using this method to delete a file but it always return true ("Delete successfully") even file is not exist on S3

``` php
if ($s3->deleteObject($bucketName, baseName($uploadFile))) {
    echo "Delete successfully";
}else{
   echo "Fail to delete";
}   

```

**Comment by tpyo** [comment]
Sorry for the late response.  The successful response is what is included in the API response, so not really related to the library.
