### ISSUE TITLE
"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."

### ISSUE THREAD

**Issue by Kulikovpavel** [tpyo/amazon-s3-php-class#120]
AWS::S3::Errors::InvalidRequest The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

I have same problem, with Frankfurt server, as in this question.
http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

Can you add new type of authorization?

**Comment by p4trizio** [comment]
same problem here

**Comment by p4trizio** [comment]
Sorry this looks a duplicate of #96

**Comment by amrutanikam** [comment]
In case some needs have a look [https://gist.github.com/andybroomfield/2383c19171f0739b77e4b831e1e9ee61]

**Comment by tpyo** [comment]
Closed in #128.

**Comment by prabhakaran-s-kt** [comment]
It seems that this was not included in the most recent version, v0.5.1. Would you kindly update the version that was released?
