### ISSUE TITLE
How getObject content without saving to file?

### ISSUE THREAD

**Issue by nezarat** [tpyo/amazon-s3-php-class#137]
I want to get the Object data without saving it to file and read it back.
Use this file:
$tmp = '/tmp/tmpfile';
S3::setAuth($app->config("app.s3_api_id"), $app->config("app.s3_api_key"));
S3::getObject($app->config("app.s3_bucket"), 'uri/to/file', $tmp);
$filecontent= file_get_contents($tmp);
 unlink($tmp);
 return $filecontent;

**Comment by ewwink** [comment]
to return as string you only need 2 parameter
```
$filecontent = S3::getObject($app->config("app.s3_bucket"), 'uri/to/file');
return $filecontent;
```
