### ISSUE TITLE
add header cache control

### ISSUE THREAD

**Issue by rickzal13** [tpyo/amazon-s3-php-class#138]
How To Add cache control header ??
can i add code..
 private $headers = array(
        'Host' => '', 'Date' => '', 'Content-MD5' => '', 'Content-Type' => '','Cache-Control' => ''
    );

to add header cache-control ??
by mine it's work.. but I need approve you to add this..
what the impact ??

**Comment by npulidom** [comment]
Set custom headers in $requestHeaders param.

```php
S3::putObject(S3::inputFile(SOME_FILE, false), BUCKET, DEST, S3::ACL_PUBLIC_READ, [], ["Cache-Control" => "max-age=864000"]);
```
