### ISSUE TITLE
AWS Signature Version 2 Deprecating from Amazon S3

### ISSUE THREAD

**Issue by lemonkazi** [tpyo/amazon-s3-php-class#152]
I got this notice from AWS.
AWS Signature Version 2 Deprecation for Amazon S3 .
I used your code in my app. is there do I have to change anything for this update?
or it's ok?

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-sig2-deprecation

**Comment by tpyo** [comment]
Closed in #128. Please try the latest master and report any issues you may find.
