### ISSUE TITLE
Disable adding bucket name as subdomain to endpoint

### ISSUE THREAD

**Issue by 4n70w4** [tpyo/amazon-s3-php-class#153]
Hi! I use custom storage server via s3 api specification.

```
$s3 = new S3('123', '456', true, 'storage.something');

S3::getObject('bucket-test', 'cert_20000.pdf');
```

`PHP Warning:  S3::getObject(bucket-test, cert_20000.pdf): [51] SSL: no alternative certificate subject name matches target host name 'bucket-test.something' in /app/vendor/tpyo/amazon-s3-php-class/S3.php on line 373
`

Problem: my server do not support subdomains for buckets.

How can I disable it or fix it differently?

**Comment by 4n70w4** [comment]
Okay. Solution:

`S3::putObject(S3::inputFile('cert_20000.pdf', false), '', 'bucket-test/cert_20000.pdf', S3::ACL_PUBLIC_READ);`

`$d = S3::getObject('', 'bucket-test/cert_20000.pdf');`

**Comment by tpyo** [comment]
Glad you figured something out.  FYI you can also disable SSL if that is acceptable to you.  That is the required approach for Amazon S3 bucket names that are not valid subdomains.
