### ISSUE TITLE
PHP 8 Issues

### ISSUE THREAD

**Issue by degive** [tpyo/amazon-s3-php-class#180]
I am trying to use the class with PHP 8 and ran into 2 issues:

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in amazon_s3/S3.php on line 2015
	$queryString = http_build_query($parameters, null, '&', PHP_QUERY_RFC3986);

Warning: S3Request::__responseWriteCallback(): Argument #1 ($curl) must be passed by reference, value given in amazon_s3/S3.php on line 2414
	if (curl_exec($curl))

Can you fix?

Thank you.

Michel

**Comment by jstanden** [comment]
As best I can tell, you just need:

```diff
Index: S3.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/S3.php b/S3.php
--- a/S3.php	(revision f11be53b79c8ccc28e336ce0cf2b1ec962d875a7)
+++ b/S3.php	(date 1662585391295)
@@ -2319,11 +2319,11 @@
 	/**
 	* CURL write callback
 	*
-	* @param resource &$curl CURL resource
-	* @param string &$data Data
+	* @param resource $curl CURL resource
+	* @param string $data Data
 	* @return integer
 	*/
-	private function __responseWriteCallback(&$curl, &$data)
+	private function __responseWriteCallback($curl, $data)
 	{
 		if (in_array($this->response->code, array(200, 206)) && $this->fp !== false)
 			return fwrite($this->fp, $data);
```

**Comment by degive** [comment]
That works! Thx
