### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

### ISSUE THREAD

**Issue by nodesocket** [tpyo/amazon-s3-php-class#46]
> The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

This error happens when attempting to upload to a bucket other than `us-standard`.

**Comment by pitashi** [comment]
This does appear to matter, at least in my use case. When instantiating the S3 object and trying to use any of the methods if I do not specify the region like this `$s3->setEndpoint('us-west-1');` it will not work. Specifically noticed this with `getObject`
