### ISSUE TITLE
S3::putObject(): [BadDigest] The Content-MD5 you specified did not match what we received. [APP/Vendor/S3/S3.php, line 355]

### ISSUE THREAD

**Issue by anupamapanchal** [tpyo/amazon-s3-php-class#89]
Hey.. we are using amazon-s3-php-class for our site http:://gridle.io with cakephp. On uploading a photo I am getting the following error.
 
S3::putObject(): [BadDigest] The Content-MD5 you specified did not match what we received. [APP/Vendor/S3/S3.php, line 355] 

Can anyone help me with this error?

**Comment by tpyo** [comment]
Closed with #99
